---

- name: CA generation
  hosts: all
  roles:
    - role: certs-generation
      when: generate_ca == "true"

- name: Elasticsearch cluster
  become: true
  vars_prompt:
    - name: cert_password
  hosts: all
  roles:
    - install-elastic
